multi-tenancy/schema-isolation/README.md
multi-tenancy/schema-isolation/pom.xml
multi-tenancy/schema-isolation/src/main/java/org/camunda/bpm/tutorial/multitenancy/ProcessDefinitionDto.java
multi-tenancy/schema-isolation/src/main/java/org/camunda/bpm/tutorial/multitenancy/TenantInterceptor.java
multi-tenancy/schema-isolation/src/test/java/org/camunda/bpm/tutorial/multitenancy/ProcessIntegrationTest.java
multi-tenancy/schema-isolation/standalone.xml
multi-tenancy/schema-isolation/standalone_test.xml

[CAM-11016] chore(multi-tenancy): upgrade example to WildFly

---

process-engine-plugin/command-interceptor-blocking/src/main/java/org/camunda/bpm/example/engine/BlockingCommandInterceptorPlugin.java

CAM-11753: Fix the interceptor registration in Camunda BPM examples

---

spring-boot-starter/example-autodeployment/README.md
spring-boot-starter/example-autodeployment/pom.xml
spring-boot-starter/example-dmn-rest/README.md
spring-boot-starter/example-dmn-rest/pom.xml
spring-boot-starter/example-dmn-rest/src/test/java/org/camunda/bpm/spring/boot/example/dmn/rest/DmnRestApplicationTest.java
spring-boot-starter/example-simple/README.md
spring-boot-starter/example-simple/pom.xml
spring-boot-starter/example-twitter/README.md
spring-boot-starter/example-twitter/pom.xml
spring-boot-starter/example-twitter/src/main/resources/TwitterDemoProcess.bpmn
spring-boot-starter/example-twitter/src/main/resources/application.yaml
spring-boot-starter/example-web/README.md
spring-boot-starter/example-web/pom.xml
spring-boot-starter/example-web/src/main/resources/application.properties
spring-boot-starter/example-web/src/main/resources/application.yml
spring-boot-starter/example-web/src/test/java/org/camunda/bpm/spring/boot/example/web/CamundaBpmRestIT.java
spring-boot-starter/example-webapp-ee/README.md
spring-boot-starter/example-webapp-ee/pom.xml
spring-boot-starter/example-webapp-ee/src/main/resources/application.yaml
spring-boot-starter/example-webapp-ee/src/main/resources/bpmn/sample.bpmn
spring-boot-starter/example-webapp/README.md
spring-boot-starter/example-webapp/pom.xml
spring-boot-starter/example-webapp/src/main/resources/application.yaml
spring-boot-starter/example-webapp/src/main/resources/bpmn/sample.bpmn

chore(release): update spring-boot examples

---

deployment/ejb-pa/README.md
deployment/ejb-pa/pom.xml
deployment/embedded-spring-rest/README.md
deployment/embedded-spring-rest/pom.xml
deployment/servlet-pa/README.md
deployment/servlet-pa/pom.xml
deployment/spring-boot/README.md
deployment/spring-boot/pom.xml
deployment/spring-servlet-pa-tomcat/README.md
deployment/spring-servlet-pa-tomcat/pom.xml
deployment/spring-servlet-pa-wildfly/README.md
deployment/spring-servlet-pa-wildfly/pom.xml
deployment/spring-wildfly-non-pa/README.md
deployment/spring-wildfly-non-pa/pom.xml

Related to CAM-11850
Please squash the commits before merging.

CAM-11850: update deployment examples

---

sdk-js/browser-forms-angular/README.md
sdk-js/browser-forms/README.md

CAM-11938: remove Internet Explorer mentions

---

servicetask/soap-service/README.md
servicetask/soap-service/pom.xml
servicetask/soap-service/src/main/resources/invokeSoapService.bpmn
servicetask/soap-service/src/test/java/org/camunda/bpm/example/servicetask/soap/MockedSoapRule.java
servicetask/soap-service/src/test/java/org/camunda/bpm/example/servicetask/soap/ServiceTaskSoapTest.java
servicetask/soap-service/src/test/resources/response_temperature_17.xml
servicetask/soap-service/src/test/resources/response_temperature_20.xml
servicetask/soap-service/src/test/resources/response_wrapper.xml

fix(servicetask): mock backend of soap example

---

cockpit/cockpit-angularjs-search-processes/README.md

chore(docs): expand AngularJS plugin documentation

---

authentication/basic/pom.xml
authentication/basic/src/main/resources/applicationContext.xml
scripttask/xquery-scripttask/pom.xml
scripttask/xslt-scripttask/pom.xml
servicetask/rest-service/pom.xml
servicetask/service-invocation-asynchronous/pom.xml
servicetask/service-invocation-synchronous/pom.xml
servicetask/soap-cxf-service/pom.xml
servicetask/soap-service/pom.xml
startevent/message-start/pom.xml
startevent/soap-cxf-server-start/pom.xml
usertask/task-assignment-email/pom.xml
usertask/task-form-embedded-bpmn-events/pom.xml
usertask/task-form-embedded-json/pom.xml
usertask/task-form-embedded-react/pom.xml
usertask/task-form-embedded-serialized-java-object/pom.xml
usertask/task-form-embedded/pom.xml
usertask/task-form-external-jsf/pom.xml
usertask/task-form-generated/pom.xml
wildfly/jackson-annotations/pom.xml

CAM-12349: chore(release): adjust bpmn examples for 7.14 release

---

sdk-js/browser-forms-angular/README.md
sdk-js/browser-forms/README.md

CAM-12570: chore(sdk-js): clarify covered use case

---

README.md
cockpit/cockpit-fullstack-count-processes/README.md
sdk-js/browser-forms-angular/README.md
sdk-js/browser-forms/README.md
sdk-js/nodejs/README.md

chore(docs): reflect merged webapps

---

cockpit/cockpit-fullstack-count-processes/README.md

chore(docs): update link to Frontend Details

---

README.md
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/README.md
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/src/main/java/org/camunda/bpm/spring/boot/example/Application.java
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/src/main/java/org/camunda/bpm/spring/boot/example/HandlerConfiguration.java
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/src/main/resources/application.yml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/src/main/resources/bpmn/workflow.bpmn
spring-boot-starter/external-task-client/loan-granting-spring/README.md
spring-boot-starter/external-task-client/loan-granting-spring/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring/src/main/java/org/camunda/bpm/spring/example/Application.java
spring-boot-starter/external-task-client/loan-granting-spring/src/main/java/org/camunda/bpm/spring/example/HandlerConfiguration.java
spring-boot-starter/external-task-client/loan-granting-spring/src/main/resources/client.properties
spring-boot-starter/external-task-client/loan-granting-spring/src/main/resources/logback.xml
spring-boot-starter/external-task-client/loan-granting-spring/workflow.bpmn
spring-boot-starter/external-task-client/order-handling-spring-boot/README.md
spring-boot-starter/external-task-client/order-handling-spring-boot/pom.xml
spring-boot-starter/external-task-client/order-handling-spring-boot/src/main/java/org/camunda/bpm/spring/boot/example/Application.java
spring-boot-starter/external-task-client/order-handling-spring-boot/src/main/java/org/camunda/bpm/spring/boot/example/HandlerConfiguration.java
spring-boot-starter/external-task-client/order-handling-spring-boot/src/main/java/org/camunda/bpm/spring/boot/example/Invoice.java
spring-boot-starter/external-task-client/order-handling-spring-boot/src/main/java/org/camunda/bpm/spring/boot/example/Subscriptions.java
spring-boot-starter/external-task-client/order-handling-spring-boot/src/main/resources/application.yml
spring-boot-starter/external-task-client/order-handling-spring-boot/workflow.bpmn
spring-boot-starter/external-task-client/request-interceptor-spring-boot/README.md
spring-boot-starter/external-task-client/request-interceptor-spring-boot/pom.xml
spring-boot-starter/external-task-client/request-interceptor-spring-boot/src/main/java/org/camunda/bpm/spring/boot/example/Application.java
spring-boot-starter/external-task-client/request-interceptor-spring-boot/src/main/java/org/camunda/bpm/spring/boot/example/InterceptorConfiguration.java
spring-boot-starter/external-task-client/request-interceptor-spring-boot/src/main/resources/application.yml
spring-boot-starter/external-task-client/request-interceptor-spring-boot/workflow.bpmn

chore(spring-boot): add xtac starter examples

---

bpmn-model-api/generate-jsf-form/pom.xml
bpmn-model-api/parse-bpmn/pom.xml
cmmn-model-api/typed-custom-elements/pom.xml
process-engine-plugin/failed-job-retry-profile/README.md
process-engine-plugin/failed-job-retry-profile/pom.xml
process-engine-plugin/failed-job-retry-profile/src/main/java/org/camunda/bpm/example/delegate/ServiceTaskOneDelegate.java
process-engine-plugin/failed-job-retry-profile/src/main/resources/retry-example.bpmn

* adjust junit version to 4.13.1
* enable logging in failed job retry example
Related to CAM-13240

chore(examples): bump plugin & models examples to 7.15

---

multi-tenancy/schema-isolation/standalone.xml
multi-tenancy/schema-isolation/standalone_test.xml
multi-tenancy/tenant-identifier-embedded/pom.xml
multi-tenancy/tenant-identifier-shared-definitions/pom.xml
spin/dataformat-configuration-in-process-application/README.md
spin/dataformat-configuration-in-process-application/src/main/runtime/wildfly/webapp/WEB-INF/jboss-deployment-structure.xml

chore(release): update misc examples

---

deployment/embedded-spring-rest/pom.xml
deployment/spring-boot/pom.xml
deployment/spring-boot/src/main/resources/application.properties
deployment/spring-boot/src/test/java/org/camunda/bpm/example/CamundaSpringBootExampleApplicationTest.java
deployment/spring-servlet-pa-wildfly/pom.xml

chore(release): update deployment examples

---

authentication/basic/pom.xml
scripttask/xquery-scripttask/pom.xml
scripttask/xslt-scripttask/pom.xml
servicetask/rest-service/pom.xml
servicetask/service-invocation-asynchronous/pom.xml
servicetask/service-invocation-synchronous/pom.xml
servicetask/soap-cxf-service/pom.xml
servicetask/soap-cxf-service/src/test/java/com/camunda/bpm/example/spring/soap/BankCustomerProcessTest.java
servicetask/soap-service/pom.xml
startevent/message-start/pom.xml
startevent/soap-cxf-server-start/pom.xml
startevent/soap-cxf-server-start/src/test/java/com/camunda/bpm/example/spring/soap/start/BankAccountProcessTest.java
usertask/task-assignment-email/pom.xml
usertask/task-form-embedded-react/config/config.js
wildfly/jackson-annotations/pom.xml
wildfly/jackson-annotations/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

chore(bpmn): bump examples to 7.15

---

deployment/spring-servlet-pa-tomcat/pom.xml
deployment/spring-servlet-pa-wildfly/pom.xml
deployment/spring-wildfly-non-pa/pom.xml

chore(deployment): bump examples to Spring 5

---

spring-boot-starter/example-autodeployment/pom.xml
spring-boot-starter/example-dmn-rest/pom.xml
spring-boot-starter/example-invoice/pom.xml
spring-boot-starter/example-simple/pom.xml
spring-boot-starter/example-twitter/pom.xml
spring-boot-starter/example-web/pom.xml
spring-boot-starter/example-webapp-ee/pom.xml
spring-boot-starter/example-webapp/pom.xml
spring-boot-starter/example-webapp/src/test/java/org/camunda/bpm/spring/boot/example/webapp/ApplicationTest.java

* bumps Spring Boot to 2.5.4
* bumps Assert to 12.0.0
* adds Graal.js where necessary so it runs on Java 15
* bumps Camunda Mockito to 5.15.0
* renames web app test so it runs on `mvn clean verify`
related to CAM-13913

chore(spring-boot-starter): adjust for 7.16 release

---

process-engine-plugin/command-interceptor-blocking/README.md
process-engine-plugin/custom-history-level/README.md
process-engine-plugin/failed-job-retry-profile/README.md

chore(process-engine-plugin): adjust for 7.16 release

---

cmmn-model-api/typed-custom-elements/README.md

chore(cmmn-model-api): adjust for 7.16 release

---

quarkus-extension/datasource-example/src/main/java/org/camunda/bpm/quarkus/example/datasource/Deployments.java
quarkus-extension/datasource-example/src/main/resources/application.properties
quarkus-extension/simple-rest-example/src/main/java/org/camunda/bpm/quarkus/example/rest/DeployProcessService.java
quarkus-extension/spin-plugin-example/src/main/java/org/camunda/bpm/quarkus/example/ResourceDeployment.java

chore(quarkus): add name to deployments

---

authentication/basic/pom.xml
authentication/basic/src/test/java/org/camunda/bpm/example/authentication/AuthenticationTest.java
scripttask/xquery-scripttask/pom.xml
scripttask/xslt-scripttask/pom.xml
servicetask/rest-service/pom.xml
servicetask/service-invocation-asynchronous/pom.xml
servicetask/service-invocation-synchronous/pom.xml
servicetask/soap-cxf-service/pom.xml
servicetask/soap-service/pom.xml
startevent/message-start/pom.xml
startevent/soap-cxf-server-start/pom.xml
usertask/task-assignment-email/pom.xml
wildfly/jackson-annotations/pom.xml
wildfly/jackson-annotations/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

CAM-14240: chore(examples): adjust bpmn examples

---

bpmn-model-api/generate-jsf-form/pom.xml
bpmn-model-api/generate-process-fluent-api/pom.xml
cmmn-model-api/typed-custom-elements/pom.xml
process-engine-plugin/bpmn-parse-listener-on-user-task/pom.xml
process-engine-plugin/bpmn-parse-listener/pom.xml
process-engine-plugin/command-interceptor-blocking/pom.xml
process-engine-plugin/custom-history-level/pom.xml
process-engine-plugin/failed-job-retry-profile/pom.xml

chore(plugin-model-api): bump versions to 7.17.0

---

spring-boot-starter/example-autodeployment/pom.xml
spring-boot-starter/example-dmn-rest/pom.xml
spring-boot-starter/example-invoice/pom.xml
spring-boot-starter/example-simple/pom.xml
spring-boot-starter/example-twitter/pom.xml
spring-boot-starter/example-web/pom.xml
spring-boot-starter/example-webapp-ee/README.md
spring-boot-starter/example-webapp-ee/pom.xml
spring-boot-starter/example-webapp/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring/pom.xml
spring-boot-starter/external-task-client/order-handling-spring-boot/pom.xml
spring-boot-starter/external-task-client/request-interceptor-spring-boot/pom.xml

chore(spring-boot): bump versions to 7.17.0

---

clients/java/dataformat/README.md
clients/java/dataformat/pom.xml
clients/java/dataformat/src/main/java/org/camunda/bpm/App.java
clients/java/loan-granting/README.md
clients/java/loan-granting/pom.xml
clients/java/order-handling/README.md
clients/java/order-handling/pom.xml

- fix typos & camunda run commands
related to CAM-14246

chore(external-task): bump versions to 7.17.0

---

dmn-engine/dmn-engine-drg/pom.xml
dmn-engine/dmn-engine-java-main-method/pom.xml
migration/migrate-on-deployment/pom.xml
multi-tenancy/schema-isolation/pom.xml
multi-tenancy/schema-isolation/standalone.xml
multi-tenancy/schema-isolation/standalone_test.xml
multi-tenancy/tenant-identifier-embedded/pom.xml
multi-tenancy/tenant-identifier-shared-definitions/pom.xml
multi-tenancy/tenant-identifier-shared/pom.xml
spin/dataformat-configuration-global/pom.xml
spin/dataformat-configuration-in-process-application/pom.xml
spin/dataformat-configuration-in-process-application/src/main/runtime/wildfly/webapp/WEB-INF/jboss-deployment-structure.xml

* Adjust DMN examples.
* Adjust Spin exampls.
* Adjust migration example.
* Adjust multi-tenancy examples.
Related to CAM-14244

CAM-14244: chore(misc): bump dependency versions

---

quarkus-extension/datasource-example/pom.xml
quarkus-extension/datasource-example/src/main/resources/application.properties
quarkus-extension/simple-rest-example/pom.xml
quarkus-extension/spin-plugin-example/pom.xml

chore(quarkus-extension): test and migrate examples

---

deployment/embedded-spring-rest/pom.xml
deployment/servlet-pa/pom.xml
deployment/spring-boot/pom.xml
deployment/spring-servlet-pa-tomcat/pom.xml
deployment/spring-servlet-pa-wildfly/pom.xml
deployment/spring-wildfly-non-pa/pom.xml

chore(deployment): prepare examples for 7.18.0

---

clients/java/dataformat/pom.xml
clients/java/loan-granting/pom.xml
clients/java/order-handling/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring/pom.xml
spring-boot-starter/external-task-client/order-handling-spring-boot/pom.xml
spring-boot-starter/external-task-client/request-interceptor-spring-boot/README.md
spring-boot-starter/external-task-client/request-interceptor-spring-boot/pom.xml

chore(client-examples): adjust external task client examples

---

quarkus-extension/datasource-example/pom.xml
quarkus-extension/simple-rest-example/pom.xml
quarkus-extension/spin-plugin-example/pom.xml

chore(quarkus): adjust quarkus extension examples

---

dmn-engine/dmn-engine-drg/pom.xml
dmn-engine/dmn-engine-java-main-method/pom.xml
migration/migrate-on-deployment/pom.xml
multi-tenancy/schema-isolation/pom.xml
multi-tenancy/tenant-identifier-embedded/pom.xml
multi-tenancy/tenant-identifier-shared-definitions/pom.xml
multi-tenancy/tenant-identifier-shared/pom.xml
spin/dataformat-configuration-global/pom.xml
spin/dataformat-configuration-in-process-application/pom.xml

chore(misc):  bumps versions to 7.18.0

---

testing/assert/job-announcement-publication-process/README.md
testing/assert/job-announcement-publication-process/pom.xml
testing/junit5/camunda-bpm-junit-assert/pom.xml
testing/junit5/camunda-bpm-junit-use-engine/pom.xml

rename the artifactId of "use-engine" project to avoid collision 
Related to CAM-14555

chore(assert): adjust assert examples

---

spring-boot-starter/example-dmn-rest/pom.xml
spring-boot-starter/example-invoice/pom.xml
spring-boot-starter/example-simple/pom.xml
spring-boot-starter/example-simple/src/main/resources/application.yaml
spring-boot-starter/example-twitter/pom.xml
spring-boot-starter/example-web/pom.xml
spring-boot-starter/example-webapp-ee/pom.xml
spring-boot-starter/example-webapp/pom.xml

chore(spring-boot): prepare examples for 7.18.0

---

usertask/task-form-embedded-react/config/react/loadReact.js
usertask/task-form-embedded-react/pom.xml
usertask/task-form-embedded-react/src/main/webapp/start-form.html
usertask/task-form-embedded-react/src/main/webapp/task-form.html

chore(usertask): bump react version to 18.0.0

---

quarkus-extension/simple-rest-example/src/main/resources/application.properties
quarkus-extension/spin-plugin-example/src/main/resources/application.properties

camunda/camunda-bpm-platform/issues/2796

chore(quarkus-examples): add h2 datasource

---

spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml

related to camunda/camunda-bpm-platform#2925

chore(xtac): adjust spring boot version

---

scripttask/xslt-scripttask/pom.xml
usertask/task-camunda-forms/pom.xml
usertask/task-form-embedded-bpmn-events/pom.xml
usertask/task-form-embedded-json-variables/pom.xml
usertask/task-form-embedded/pom.xml
wildfly/jackson-annotations/README.md
wildfly/jackson-annotations/pom.xml
wildfly/jackson-annotations/src/main/java/org/camunda/examples/JacksonAnnotationApplication.java
wildfly/jackson-annotations/src/main/webapp/WEB-INF/jboss-deployment-structure.xml

related to camunda/camunda-bpm-platform#2918

chore(bpmn2.0): adjust examples

---

bpmn-model-api/generate-process-fluent-api/pom.xml
bpmn-model-api/parse-bpmn/pom.xml
process-engine-plugin/bpmn-parse-listener/pom.xml
process-engine-plugin/command-interceptor-blocking/pom.xml
process-engine-plugin/custom-history-level/pom.xml
process-engine-plugin/failed-job-retry-profile/pom.xml

closes https://github.com/camunda/camunda-bpm-platform/issues/2920

2920: Adjust plugins and model API examples

---

spring-boot-starter/example-invoice/pom.xml
spring-boot-starter/example-simple/pom.xml
spring-boot-starter/example-twitter/pom.xml
spring-boot-starter/example-web/pom.xml
spring-boot-starter/example-webapp-ee/README.md
spring-boot-starter/example-webapp-ee/pom.xml
spring-boot-starter/example-webapp/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/README.md

related to camunda/camunda-bpm-platform/issues/2923

2923 migrate spring boot examples

---

quarkus-extension/datasource-example/pom.xml
quarkus-extension/spin-plugin-example/README.md
quarkus-extension/spin-plugin-example/pom.xml

related to camunda/camunda-bpm-platform#2924

chore(quarkus): adjust examples

---

README.md

https://github.com/camunda/camunda-bpm-platform/issues/2734

chore(readme): add not maintained note

---

process-engine-plugin/handling-jpa-variables/README.md
process-engine-plugin/handling-jpa-variables/pom.xml
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/entities/Customer.java
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/variables/serializer/EntityManagerSession.java
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/variables/serializer/EntityManagerSessionFactory.java
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/variables/serializer/EntityManagerSessionImpl.java
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/variables/serializer/EntityMetaData.java
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/variables/serializer/JPAEntityMappings.java
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/variables/serializer/JPAEntityScanner.java
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/variables/serializer/JPAVariableSerializer.java
process-engine-plugin/handling-jpa-variables/src/main/java/org/camunda/bpm/example/jpa/variables/serializer/JPAVariablesSerializerPlugin.java
process-engine-plugin/handling-jpa-variables/src/test/java/org/camunda/bpm/example/test/JPAVariableTest.java
process-engine-plugin/handling-jpa-variables/src/test/resources/META-INF/persistence.xml
process-engine-plugin/handling-jpa-variables/src/test/resources/camunda.cfg.xml
process-engine-plugin/handling-jpa-variables/src/test/resources/process.bpmn

https://github.com/camunda/camunda-bpm-platform/issues/3447

chore(examples): add JPA variable serializer example

---

spring-boot-starter/example-invoice/README.md
spring-boot-starter/example-invoice/pom.xml
spring-boot-starter/example-invoice/src/main/java/org/camunda/bpm/spring/boot/example/invoice/InvoiceApplication.java
spring-boot-starter/example-simple/README.md
spring-boot-starter/example-simple/pom.xml
spring-boot-starter/example-twitter/README.md
spring-boot-starter/example-twitter/pom.xml
spring-boot-starter/example-web/README.md
spring-boot-starter/example-web/pom.xml
spring-boot-starter/example-web/src/test/java/org/camunda/bpm/spring/boot/example/web/CamundaBpmRestTest.java
spring-boot-starter/example-webapp-ee/README.md
spring-boot-starter/example-webapp-ee/pom.xml
spring-boot-starter/example-webapp/README.md
spring-boot-starter/example-webapp/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/README.md
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml
testing/assert/job-announcement-publication-process/README.md
testing/assert/job-announcement-publication-process/pom.xml

https://github.com/camunda/camunda-bpm-platform/issues/3444

chore(starter): Spring Boot 3.1 support

---

scripttask/xslt-scripttask/pom.xml

related to camunda/camunda-bpm-platform#3697

chore(scripttask): adjust xslt example

---

testing/assert/job-announcement-publication-process/pom.xml
testing/junit5/camunda-bpm-junit-assert/pom.xml
testing/junit5/camunda-bpm-junit-use-engine/pom.xml

related to https://github.com/camunda/camunda-bpm-platform/issues/3331

chore(testing): adjust to 7.20

---

bpmn-model-api/generate-process-fluent-api/pom.xml
bpmn-model-api/generate-process-fluent-api/src/test/java/org/camunda/bpm/quickstart/CreateInvoiceProcessTest.java
bpmn-model-api/parse-bpmn/pom.xml
process-engine-plugin/bpmn-parse-listener/pom.xml
process-engine-plugin/command-interceptor-blocking/pom.xml
process-engine-plugin/custom-history-level/pom.xml
process-engine-plugin/failed-job-retry-profile/pom.xml
process-engine-plugin/handling-jpa-variables/pom.xml

Related-to: https://github.com/camunda/camunda-bpm-platform/issues/3325

chore(bpmn-model-api): Add historyTimeToLive to Test

---

spring-boot-starter/example-invoice/pom.xml
spring-boot-starter/example-simple/pom.xml
spring-boot-starter/example-twitter/pom.xml
spring-boot-starter/example-web/pom.xml
spring-boot-starter/example-webapp-ee/pom.xml
spring-boot-starter/example-webapp/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml

Related-to: https://github.com/camunda/camunda-bpm-platform/issues/3328

chore(spring-boot-starter): Set Maven Compiler Level 11

---

quarkus-extension/datasource-example/README.md
quarkus-extension/datasource-example/pom.xml
quarkus-extension/datasource-example/src/main/java/org/camunda/bpm/quarkus/example/datasource/ApprovalServiceBean.java
quarkus-extension/datasource-example/src/main/java/org/camunda/bpm/quarkus/example/datasource/ApprovalServiceDelegate.java
quarkus-extension/datasource-example/src/main/java/org/camunda/bpm/quarkus/example/datasource/Deployments.java
quarkus-extension/datasource-example/src/main/java/org/camunda/bpm/quarkus/example/datasource/rest/ApprovalProcessService.java
quarkus-extension/datasource-example/src/test/java/org/camunda/bpm/quarkus/example/datasource/ApprovalProcessTest.java
quarkus-extension/spin-plugin-example/README.md
quarkus-extension/spin-plugin-example/pom.xml
quarkus-extension/spin-plugin-example/src/main/java/org/camunda/bpm/quarkus/example/EngineConfiguration.java
quarkus-extension/spin-plugin-example/src/main/java/org/camunda/bpm/quarkus/example/ResourceDeployment.java
quarkus-extension/spin-plugin-example/src/main/java/org/camunda/bpm/quarkus/example/rest/StartProcessRestResource.java
quarkus-extension/spin-plugin-example/src/main/java/org/camunda/bpm/quarkus/example/service/StoreOrderItemService.java

related to camunda/camunda-bpm-platform#3418

chore(quarkus): update examples to quarkus3

---

README.md
deployment/ejb-pa-jakarta/pom.xml
deployment/ejb-pa/pom.xml
deployment/embedded-spring-rest/README.md
deployment/embedded-spring-rest/pom.xml
deployment/servlet-pa/pom.xml
deployment/spring-servlet-pa-tomcat/README.md
deployment/spring-servlet-pa-tomcat/pom.xml
deployment/spring-servlet-pa-wildfly/README.md
deployment/spring-servlet-pa-wildfly/pom.xml
deployment/spring-wildfly-non-pa/README.md
deployment/spring-wildfly-non-pa/pom.xml

related to camunda/camunda-bpm-platform#3324

chore(deployment): adjust to 7.20

---

cockpit/cockpit-bpmn-js-module-bundled/dist/custom-renderer-module-bundled.js
cockpit/cockpit-bpmn-js-module-bundled/package-lock.json
cockpit/cockpit-bpmn-js-module-bundled/package.json
cockpit/cockpit-fullstack-count-processes/frontend/package-lock.json
cockpit/cockpit-fullstack-count-processes/frontend/package.json
cockpit/cockpit-fullstack-count-processes/pom.xml
cockpit/cockpit-react-involved-users/package-lock.json
cockpit/cockpit-react-involved-users/package.json

related to camunda/camunda-bpm-platform#3326

chore(webapps): adjust to 7.20

---

dmn-engine/dmn-engine-drg/pom.xml
dmn-engine/dmn-engine-drg/src/main/resources/org/camunda/bpm/example/drg/dinnerDecisions.dmn
dmn-engine/dmn-engine-java-main-method/pom.xml
migration/migrate-on-deployment/pom.xml
multi-tenancy/schema-isolation/pom.xml
multi-tenancy/tenant-identifier-embedded/pom.xml
multi-tenancy/tenant-identifier-shared-definitions/pom.xml
multi-tenancy/tenant-identifier-shared/pom.xml
spin/dataformat-configuration-global/pom.xml
spin/dataformat-configuration-in-process-application/pom.xml

https://github.com/camunda/camunda-bpm-platform/issues/3327

chore(misc): switch to Java 11 source code level

---

clients/java/order-handling/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml

related to camunda/camunda-bpm-platform#3330

chore(client/java): update XTaC examples

---

clients/java/order-handling/README.md
clients/java/order-handling/src/main/java/org/camunda/bpm/App.java

related to https://github.com/camunda/camunda-bpm-platform/issues/3944

chore(clients/java): add customizeHttpClient

---

clients/java/order-handling/pom.xml
spring-boot-starter/example-web/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml

https://github.com/camunda/camunda-bpm-platform/issues/3829

chore(clients): adjust dependencies

---

quarkus-extension/datasource-example/pom.xml
quarkus-extension/spin-plugin-example/pom.xml

https://github.com/camunda/camunda-bpm-platform/issues/3843

chore(quarkus-extension): update to Quarkus 3.8.3

---

wildfly/jackson-annotations/README.md
wildfly/jackson-annotations/pom.xml

related to https://github.com/camunda/camunda-bpm-platform/issues/3837

chore(wildfly): update jackson wildfly example

---

deployment/ejb-pa/README.md
deployment/servlet-pa/README.md
deployment/spring-servlet-pa-tomcat/pom.xml
deployment/spring-servlet-pa-wildfly/README.md
deployment/spring-wildfly-non-pa/README.md

related to https://github.com/camunda/camunda-bpm-platform/issues/3838

chore(deployment): update examples to 7.21

---

spin/dataformat-configuration-global/README.md
spin/dataformat-configuration-in-process-application/README.md

https://github.com/camunda/camunda-bpm-platform/issues/3841

chore(spin): migrate to 7.21

---

testing/assert/job-announcement-publication-process/README.md
testing/assert/job-announcement-publication-process/pom.xml
testing/junit5/camunda-bpm-junit-assert/pom.xml
testing/junit5/camunda-bpm-junit-use-engine/pom.xml

related to https://github.com/camunda/camunda-bpm-platform/issues/3846

chore(testing): update examples to 7.21

---

spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/README.md
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml

related to https://github.com/camunda/camunda-bpm-platform/issues/3844

chore(spring-boot): update examples to 7.21

---

cockpit/cockpit-bpmn-js-module-bundled/package-lock.json
cockpit/cockpit-bpmn-js-module-bundled/package.json
cockpit/cockpit-fullstack-count-processes/frontend/package-lock.json
cockpit/cockpit-fullstack-count-processes/frontend/package.json
cockpit/cockpit-react-involved-users/package-lock.json
cockpit/cockpit-react-involved-users/package.json

related to: camunda/camunda-bpm-platform/issues/3840

chore(cockpit): update for 7.21

---

quarkus-extension/datasource-example/pom.xml
quarkus-extension/spin-plugin-example/pom.xml

Related to https://github.com/camunda/camunda-bpm-platform/issues/4261

chore(release): adjust quarkus-extension examples

---

spring-boot-starter/example-invoice/pom.xml
spring-boot-starter/example-simple/pom.xml
spring-boot-starter/example-twitter/pom.xml
spring-boot-starter/example-web/pom.xml
spring-boot-starter/example-webapp-ee/pom.xml
spring-boot-starter/example-webapp/pom.xml
spring-boot-starter/external-task-client/loan-granting-spring-boot-webapp/pom.xml

Related to https://github.com/camunda/camunda-bpm-platform/issues/4260

chore(spring-boot): bump spring-boot-starter examples to 7.22

---

README.md
deployment/embedded-spring-rest/README.md
deployment/embedded-spring-rest/pom.xml
deployment/embedded-spring-rest/src/main/java/org/camunda/bpm/example/loanapproval/rest/RestProcessEngineDeployment.java
deployment/embedded-spring-rest/src/main/webapp/WEB-INF/web.xml
deployment/spring-servlet-pa-tomcat/README.md
deployment/spring-servlet-pa-tomcat/pom.xml
deployment/spring-servlet-pa-wildfly/README.md
deployment/spring-servlet-pa-wildfly/pom.xml
deployment/spring-wildfly-non-pa/pom.xml

https://github.com/camunda/camunda-bpm-platform/issues/4256

chore(deployment): migrate to 7.22

---

bpmn-model-api/generate-process-fluent-api/pom.xml
bpmn-model-api/parse-bpmn/pom.xml
pom.xml
process-engine-plugin/bpmn-parse-listener/pom.xml
process-engine-plugin/command-interceptor-blocking/pom.xml
process-engine-plugin/custom-history-level/pom.xml
process-engine-plugin/failed-job-retry-profile/pom.xml
process-engine-plugin/handling-jpa-variables/pom.xml

related to https://github.com/camunda/camunda-bpm-platform/issues/4257

chore(model-api): update examples to 7.22

---

scripttask/xslt-scripttask/pom.xml
servicetask/rest-service/pom.xml
servicetask/service-invocation-asynchronous/pom.xml
servicetask/service-invocation-synchronous/pom.xml
startevent/message-start/pom.xml
usertask/task-camunda-forms/README.md
usertask/task-camunda-forms/pom.xml
usertask/task-camunda-forms/src/main/java/org/camunda/bpm/usertask/camundaforms/CamundaFormPa.java
usertask/task-form-embedded-bpmn-events/README.md
usertask/task-form-embedded-bpmn-events/pom.xml
usertask/task-form-embedded-bpmn-events/src/main/java/org/camunda/bpm/quickstart/usertask/EmbeddedTaskFormPa.java
usertask/task-form-embedded-json-variables/README.md
usertask/task-form-embedded-json-variables/pom.xml
usertask/task-form-embedded-json-variables/src/main/java/org/camunda/bpm/example/JsonProcessApplication.java
usertask/task-form-embedded-react/README.md
usertask/task-form-embedded-react/pom.xml
usertask/task-form-embedded-react/src/main/java/org/camunda/bpm/quickstart/react/EmbeddedTaskFormReactPa.java
usertask/task-form-embedded/README.md
usertask/task-form-embedded/pom.xml
usertask/task-form-embedded/src/main/java/org/camunda/bpm/quickstart/usertask/EmbeddedTaskFormPa.java
wildfly/jackson-annotations/README.md

Related to https://github.com/camunda/camunda-bpm-platform/issues/4255

4255 bpmn examples

---

cockpit/cockpit-bpmn-js-module-bundled/dist/custom-renderer-module-bundled.js
cockpit/cockpit-bpmn-js-module-bundled/package-lock.json
cockpit/cockpit-bpmn-js-module-bundled/package.json
cockpit/cockpit-fullstack-count-processes/frontend/package-lock.json
cockpit/cockpit-fullstack-count-processes/frontend/package.json
cockpit/cockpit-fullstack-count-processes/pom.xml
cockpit/cockpit-react-involved-users/package-lock.json
cockpit/cockpit-react-involved-users/package.json

related to: camunda/camunda-bpm-platform/issues/4258

chore(webapps):  adjust to 7.22

---

dmn-engine/dmn-engine-drg/pom.xml
dmn-engine/dmn-engine-java-main-method/README.md
dmn-engine/dmn-engine-java-main-method/pom.xml
spin/dataformat-configuration-in-process-application/pom.xml
spin/dataformat-configuration-in-process-application/src/main/runtime/wildfly/webapp/WEB-INF/jboss-deployment-structure.xml

Related-to: https://github.com/camunda/camunda-bpm-platform/issues/4259

chore(dmn): Adjust and Migrate

---

bpmn-model-api/generate-process-fluent-api/pom.xml
bpmn-model-api/parse-bpmn/pom.xml
process-engine-plugin/bpmn-parse-listener/pom.xml
process-engine-plugin/command-interceptor-blocking/pom.xml
process-engine-plugin/custom-history-level/pom.xml
process-engine-plugin/failed-job-retry-profile/pom.xml
process-engine-plugin/handling-jpa-variables/pom.xml

Related to https://github.com/camunda/camunda-bpm-platform/issues/4692

chore(examples): update to jdk 17 in plugin & model api examples

---

quarkus-extension/datasource-example/README.md
quarkus-extension/datasource-example/pom.xml
quarkus-extension/spin-plugin-example/README.md
quarkus-extension/spin-plugin-example/pom.xml

related to camunda/camunda-bpm-platform#4696

chore(quarkus): update examples for 7.23.0 release

---

testing/assert/job-announcement-publication-process/pom.xml
testing/junit5/camunda-bpm-junit-assert/README.md
testing/junit5/camunda-bpm-junit-assert/pom.xml
testing/junit5/camunda-bpm-junit-use-engine/README.md
testing/junit5/camunda-bpm-junit-use-engine/pom.xml

https://github.com/camunda/camunda-bpm-platform/issues/4699

chore(assert): update to latest version
